### ISSUE TITLE
Losing lots of tweets when hydrating

### ISSUE THREAD

**Issue by sanand100** [DocNow/hydrator#108]
Hello! 

I hope you are doing well and thank you so much for providing us with this tool! 

I am trying to hydrate tweets, and I keep having a lot of my tweets deleted. For example, I input 30 tweet IDs and only 4 are hydrated. Could you please help me figure out why this is happening? Thank you!

**Comment by edsu** [comment]
This is a common problem when the tweet id dataset has been opened and then saved with Excel since it does not hander large numbers well. One indicator that this has happened is if all the tweet ids end in a zero (0).
