### ISSUE TITLE
Number of hydrated tweets vastly smaller than rows in resulting CSV

### ISSUE THREAD

**Issue by soursunrise** [DocNow/hydrator#110]
Hi,

I have recently hydrated 8,742,424 tweet IDs, the output shows 5,550,148 tweets extracted (deletion rate was high). However, when I load the resulting CSV in R, it shows 10,495,674 rows/tweets. How can this be? 

Thanks for your answer!

V

**Comment by igorbrigadir** [comment]
How exactly are you loading the file in R? 

Someone else on on the docnow slack had an issue with R but it was resolved when using `tidyverse` as opposed to `read.csv()`

**Comment by soursunrise** [comment]
I've been using `read_csv`, yes, but it's part of `tidyverse`, as far as I understand? What would you suggest?

**Comment by edsu** [comment]
I'm curious does each row in the DataFrame have an id?

**Comment by soursunrise** [comment]
Turns out that it was a divider problem in the `write.csv2()` which was then incorrectly uploaded.
Now the number makes sense - still a bit smaller than given by Hydrator, but I guess that was already looked at in another thread and is not differing much in any case
