### ISSUE TITLE
Perpetually "Verifying Microsoft Excel.app"

### ISSUE THREAD

**Issue by kittenzonfire** [DocNow/hydrator#113]
I've successfully run Hydrator on my laptop (a Macbook) several times in the past, but when I opened it up a couple months ago I found that I'm not able to use it because I can't upload any data. The "Select Tweet ID File" option is greyed out and there's a flashing message that says "Verifying Microsoft Excel.app..." Any way to resolve this?

<img width="489" alt="Screen Shot 2021-12-06 at 1 18 16 PM" src="https://user-images.githubusercontent.com/38921732/144924926-21bf715c-a900-4893-b87e-a4cee9203201.png">

**Comment by edsu** [comment]
It looks like you are trying to load tweets from a file named `Microsoft Excel.app`?

**Comment by kittenzonfire** [comment]
I'm not, not on purpose anyway. It just says that every time I open Hydrator, even after reinstalling.

**Comment by edsu** [comment]
Have you tried going to Settings and resetting?

**Comment by kittenzonfire** [comment]
That seemed to fix it. :)
Thanks!

**Comment by edsu** [comment]
I'm glad that worked! Sorry for the trouble.
