### ISSUE TITLE
The link Twitter account is invalid

### ISSUE THREAD

**Issue by yihong623** [DocNow/hydrator#128]
After I open the Gui, I link the twitter account and enter the pin number, but it keeps showing invalid.![image](https://user-images.githubusercontent.com/21210044/173146683-c2fcecf2-0b1a-49d0-bc18-eef0b8c0e214.png)

**Comment by edsu** [comment]
Unfortunately Hydrator does not work in environments where you aren't able to talk directly to `twitter.com`. Is it possible you are in China and using a proxy? We do have an issue for Hydrator to respect a system wide proxy, but it doesn't currently do that yet:

https://github.com/DocNow/hydrator/issues/114

**Comment by yihong623** [comment]
> Unfortunately Hydrator does not work in environments where you aren't able to talk directly to `twitter.com`. Is it possible you are in China and using a proxy? We do have an issue for Hydrator to respect a system wide proxy, but it doesn't currently do that yet:
> 
> #114

I am not in China. I used it in USA and I used it on Windows. I put my consumer key and key secret on the .env and I did click allow th access and enter the pin number but it keeps saying its invalid.

**Comment by edsu** [comment]
You may not have your app configured correctly. Hydrator uses the v1.1 API. Is there a reason why you didn't want to use the pre-built download?

**Comment by yihong623** [comment]
> You may not have your app configured correctly. Hydrator uses the v1.1 API. Is there a reason why you didn't want to use the pre-built download?

I am trying to use this for this repo https://github.com/echen102/COVID-19-TweetIDs
I am using windows. What do you mean by pre-built Hydrator? Is this on pip or an app that I can download for it? How can I configure right for this?

**Comment by edsu** [comment]
Download from here:

https://github.com/DocNow/hydrator/releases/tag/v0.3.0
