### ISSUE TITLE
Hydrator Error

### ISSUE THREAD

**Issue by Bgerrity9** [DocNow/hydrator#131]
Hello,
When I attempt to upload a csv file, I am getting an "error- invalid tweet ID on line 1" pop up window. I have no idea how to get around this, any help would be appreciated, thank you.

**Comment by edsu** [comment]
What does row 1 of your CSV look like? Note, it should be a file of just numbers, no column headers or other things:

```
13434324324234324
098947209029207027
02348098403985091
```

**Comment by Bgerrity9** [comment]
Thanks for the response, unfortunately I can't send a screenshot through here. But, If I was to open the excel file from the cvs file I have 2 columns, the first is the tweet ID and the 2nd is what I believe to be the sentiment score.

These data sets are ones I obtained from dataport regarding covid sentiment, that other researchers appear to have hydrated as well.

**Comment by igorbrigadir** [comment]
> If I was to open the excel file from the cvs file

I would advise against this. Excel corrupts IDs unfortunately, so if you're trying to modify the CSV somehow i'd recommend Google sheets instead.

**Comment by edsu** [comment]
Your id file needs to have one tweet id per line and no other information.

**Comment by Bgerrity9** [comment]
Noted, I won't open the files in excel, thanks. As the files have 2 columns, what do you suggest doing? .. When I select a tweet ID file straight into the hydrator without opening it, the same issue arises.  Right now I am opening the file with "7-Zip File manager"

**Comment by igorbrigadir** [comment]
That will need some extra work - importing it into Google sheets, removing the extra columns and headers, and then exporting it as a CSV there should work.
