### ISSUE TITLE
Hydrator suddenly stopped hydrating tweets on multiple computers

### ISSUE THREAD

**Issue by sscoggins** [DocNow/hydrator#142]
Using this for a class and multiple people were suddenly unable to use the hydrator starting 4/4/23. We can add datasets but it won't run when pressing start. I tried uninstalling and reinstalling, but the issue persists. Any help is appreciated!

**Comment by Arukou-Arukou** [comment]
> Using this for a class and multiple people were suddenly unable to use the hydrator starting 4/4/23. We can add datasets but it won't run when pressing start. I tried uninstalling and reinstalling, but the issue persists. Any help is appreciated!

I'm having the same thing happen. I suspect the overhaul of the API has probably made the program unusable.

**Comment by k1n3** [comment]
i have the same problem here . hope they can fix it soon .

**Comment by edsu** [comment]
See #143 :-(
