### ISSUE TITLE
Entire Application not functioning 

### ISSUE THREAD

**Issue by JhCandiceYao** [DocNow/hydrator#143]
I was trying to reset the API keys but as soon as I clicked on the button, everything became unclickable in my hydrator and it wouldn't be fixed by reinstalling and restarting my laptop. Anyone encountered the same issue? I suspect this has something to do with the Twitter API thing, but that shouldn't be causing the application itself to crash. Also, I tried writing codes to hydrate directly with the API and it still works for now.

**Comment by edsu** [comment]
Sadly, Twitter has revoked the keys for the app. Given their plans to limit read access it looks like Hydrator's days of helping people constitute tweet id datasets are over.

<img width="1676" alt="Screenshot 2023-04-18 at 9 38 00 AM" src="https://user-images.githubusercontent.com/33829/232795304-fd4e2615-06e0-4668-8abc-eb33d2b4e652.png">
