### ISSUE TITLE
Linking Twitter Account to Hydrator

### ISSUE THREAD

**Issue by skhosanam** [DocNow/hydrator#145]
I am tryign to link my account with the hydrator, which I want to use to retrieve tweets from tweet_ids. The issue tthat I am facing is that the "Link Twitter Account" on hydrator is "unreponsive".  If there is someone out here who can advise me as to how I should go about this. I have uninstalled the hydrator multiple times and still not luck. I will appreciate a "step-by-step" guidance on this.

**Comment by edsu** [comment]
Twitter has cancelled the Hydrator (suspended its app keys) sorry!
