### ISSUE TITLE
Link Twitter Account button not working

### ISSUE THREAD

**Issue by neethupavithran** [DocNow/hydrator#147]
Hi, I downloaded the hydrator tool but the Link Twitter Account button isn't working. I've tried closing it and re-opening a bunch of times, and ensuring that the app is allowed through my firewall. Any advice? I'm accessing on a Windows PC

**Comment by edsu** [comment]
Unfortunately Twitter revoked the application keys for Hydrator. If you have your own keys it should in theory still work, if you do your own build. But the API quota limits for hydration are so low that it probably isn't worth the trouble. Sorry I can't be of more help.
