### ISSUE TITLE
Hydrator slowing down

### ISSUE THREAD

**Issue by kkk279** [DocNow/hydrator#15]
I noticed that hydrator slowed down to a snail's pace when hydrating 18,000,000 plus tweet ids. Hydrator should have taken approximately 50 hours but it is currently 49 hours and its barely scratched the 7,000,000 tweet mark. It's currently churning out at a rate of 1400 tweets per minute and translates to 84000 per hour. Could you look into this?

**Comment by edsu** [comment]
Yes, sorry for the delayed response. I think this is an issue with the way the Hydrator is reading into the tweet id file everytime to figure out the next set of 100 tweets to retrieve. I'm going to be spending some time updating the Hydrator in the coming weeks and will look into what can be done to improve this.

I imagine you have moved off from this issue a long time ago. But in case you haven't you may want to look at using [twarc](https://github.com/docnow/twarc) to hydrate large datasets like this until the performance of Hydrator has been improved.

**Comment by edsu** [comment]
This **really** needs to get fixed since Hydrator is being increasingly used on large, unsegmented tweet ID datasets.

**Comment by kkk279** [comment]
Thanks for your response. I switched to using twarc to hydrate the files (And have since then). I hope the issue has now been resolved?

**Comment by edsu** [comment]
Not yet, sadly. But I'm working on it now.

**Comment by edsu** [comment]
The one advantage of waiting a year (or more) to address an issue is that what once seemed to be hard is now easy. It looks like Node's documentation has an example of reading a file line by line, which ought to do the trick:

https://nodejs.org/api/readline.html#readline_example_read_file_stream_line_by_line

**Comment by kkk279** [comment]
Yes, going the Nodejs route should work. Sometimes, time is the solution :-)


Regards
Kelvin
*Kiiki*

**Comment by edsu** [comment]
This fix should be available in the v0.0.6 release of Hydrator if you want to give it a try! I feel bad it took so long to address this, but better late then never?

**Comment by kkk279** [comment]
Thanks Ed. I am about to give hydrator a shot with a large dataset. Sorry
for the delay in responding, as I was preparing for the defense of my
dissertation.

Best
Kelvin

**Comment by edsu** [comment]
Did you defend already?!?!

**Comment by kkk279** [comment]
Yes I successfully defended.  :-)


Best
Kelvin

**Comment by kkk279** [comment]
Hello Ed,

I hope you are doing well. I keep getting this error when I use Hydrator
(find attached ). A little background. There were  a set of daily tweet ids
that I needed to hydrate. In order to save time, I merged all tweets into
one file (weekly tweets) and then "hydrate". I do not get the same error
message using twarc. What do you think?

Best Regards
*Kiiki*

**Comment by edsu** [comment]
What's the error?

**Comment by kkk279** [comment]
It says "invalid tweet id on line 34086532 in C:\Users..."

Best
Kelvin

**Comment by edsu** [comment]
Ah I bet you have a blank line there, or something that is not a number? Are you having trouble seeing what is there because the file is so big?

**Comment by kkk279** [comment]
Yes. I have tried looking for the line but couldnt find it. Its a big file.

Best
Kelvin

Sent From Kiiki's V20

**Comment by kkk279** [comment]
For context, even though it says that there's an invalid character in line
34086532. The total number of lines is under 30000000. Thanks.


Best
Kelvin

**Comment by kkk279** [comment]
What I ended up doing was copying the tweets to a new file and renaming it.
That solved the issue. The total number of tweets and the size of the file
remained the same. Might be a bug that throws its line counts off?

Best
Kelvin

**Comment by edsu** [comment]
It sounds like a big file, but if you can share it with me I will take a look.

**Comment by kkk279** [comment]
Sure, do you have a link or google drive you want me to drop the files to?

Best
Kelvin

**Comment by kkk279** [comment]
I have shared the file with you. You should receive the link momentarily

Best
Kelvin

**Comment by edsu** [comment]
Ah yes, I see there is a control-Z (0x1a) on the last line of the file. If you remove that you should be fine.

**Comment by kkk279** [comment]
Oh I did. But it still gave me an error message. What helped was recopying
the entire contents unto a new txt file. After that it worked.

Best
Kelvin

Sent From Kiiki's V20

**Comment by Bgerrity9** [comment]
Hello, I am getting a "Tweet ID file error - Invalid tweet ID on line 1" 
I saw on another page that I shouldn't even be opening the excel file as it corrupts the data, so I'm not sure away around this. Any help would be great, thanks.
