### ISSUE TITLE
Generated CSV file does not contain tweets

### ISSUE THREAD

**Issue by Ellime** [DocNow/hydrator#16]
After my first use of Hydrator (hydrated one set of tweets successfully) any set of Tweet IDs uploaded to Hydrator produce a CSV file with absolutely nothing - size 0 bytes. Including the first set that went through successfully.

Already tried reinstalling.
Running Windows 10.

**Comment by edsu** [comment]
Did the hydration process create a JSON file? Can you share that in some way with me at ehs@pobox.com?

**Comment by edsu** [comment]
I just started up a Windows Server 2019 instance in Amazon EC2 (I don't own a WIndows computer) and tried out the Hydrator. I was able to hydrate and create a CSV out of the hdyrated JSON. Admittedly the process is a bit clunky, and could be improved. But I think it's working?

![Screen Shot 2019-04-02 at 3 47 07 PM](https://user-images.githubusercontent.com/33829/55431544-d4622780-555e-11e9-865b-c708e42da533.png)

**Comment by edsu** [comment]
Whoops, I didn't mean to close that yet!

**Comment by Ellime** [comment]
Thank you for looking into it for me! It turns out I just wasn't following the correct steps:
* After pressing start, save a file without any extension.
* Then you can save a CSV file as normal.

Sorry for incorrectly opening an issue.

**Comment by edsu** [comment]
No it's fine. As you discovered the workflow is not intuitive. If you have ideas for improving it please let us know!
