### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by ZiranLi** [DocNow/hydrator#17]
I tried to use Hydrator in OS X and while hydrating the tweet ids, it throws an exception: Uncaught Exception: Error: EFBIG: file too large, write.
Anyone knows how to solve it?

**Comment by ZiranLi** [comment]
I tried to use Hydrator in OS X and while hydrating the tweet ids, it throws an exception: Uncaught Exception: Error: EFBIG: file too large, write.
Anyone knows how to solve it?

**Comment by edsu** [comment]
It sounds like you ran out of disk space?
