### ISSUE TITLE
hydrator keeps crashing

### ISSUE THREAD

**Issue by olubadmus** [DocNow/hydrator#21]
Ran intoerror. Won't work. Uninstalled, reinstalled but still  showing error. Any solution?

**Comment by edsu** [comment]
Can you provide some more details:

- Can you share the tweet id dataset you are working with.
- When does it crash (immediately on startup; when entering metadata; when starting to hydrate; etc)

**Comment by olubadmus** [comment]
I was hydrating a tweetset from Havard Dataverse (charlotsville) but my system froze during the process. I had to force shut down. Upon recovery, Hydrator wouldnt work, tried resinstaling it several times but kept getting the error (below) upon running the app. 
![Annotation 2019-12-27 131816](https://user-images.githubusercontent.com/39098836/71548955-ba396680-2983-11ea-8e26-05082b1119f3.png)

**Comment by edsu** [comment]
Does that error message allow you to scroll to the right?

Also, can you re-download the tweet-id dataset to make sure it hasn't been somehow corrupted?

**Comment by edsu** [comment]
Hopefully the recently released v0.0.6 release of Hydrator will resolve this problem. Please feel to reopen if that is not the case.
