### ISSUE TITLE
Tweets are limited to 140 characters

### ISSUE THREAD

**Issue by shayanshams66** [DocNow/hydrator#24]
Hi,
Currently the fetched tweets are limited to 140 characters. see below:
"display_text_range":[0,140].
Is there any option to fetch all 280 chars.
Thanks

**Comment by edsu** [comment]
Can you paste a JSON object for a tweet you received -- or the tweet id of one you are having trouble with? You should find the full 280 characters of the tweet in the `full_text` property.

**Comment by shayanshams66** [comment]
Thanks for the prompt response, Here is one tweet ID that I have problem with but there are many 1221739807711232000.
Thanks a lot

**Comment by edsu** [comment]
Thanks! This is some peculiar behavior from the Twitter API. When a retweeted tweet is > 140 characters the retweet has a shortened form. Take a look in `retweeted_status.full_text` for the original text. Do you see that?

**Comment by shayanshams66** [comment]
Yes, got it thanks a lot, I don't know why i didn't notice that.

**Comment by edsu** [comment]
It's easy to miss.
