### ISSUE TITLE
Link Twitter Account not working on Windows 10

### ISSUE THREAD

**Issue by jsutxhx** [DocNow/hydrator#27]
Thanks for the contributor share me with this app. When I install the hydrator in Windows. run it and when I click the 'Link Twitter Account' or any other function button. the app did not response. and I can't do anything with it.
Is there some configuration should do in Windows platform to run it?

**Comment by edsu** [comment]
Was your computer connected to the internet at the time?

**Comment by jsutxhx** [comment]
Yes, I connect the internet with VPN.

**Comment by jsutxhx** [comment]
I can visit the Twitter website when I surf with the VPN, and it doesn't work with the hydrator software.

**Comment by edsu** [comment]
What version of windows are you using? I dont have access to Windoes but I can try to test.

**Comment by jsutxhx** [comment]
The Windows version is Win10 Home Edition. Thanks a lot.

**Comment by kilitougo** [comment]
I had the same problem, did you solve it?

**Comment by edsu** [comment]
No I still need to test :-( I will prioritize that though.

**Comment by plumcola** [comment]
Here is Win10 and I had the same problem, too : (

**Comment by edsu** [comment]
I'm working on updating the Hydrator code base so I can better diagnose this problem. I apologize for the delay. If you need to start hydrating now,  and aren't turned off by dabbling at the command line, take a look at our other tool twarc: https://github.com/docnow/twarc#hydrate

**Comment by edsu** [comment]
So I got a chance to test v0.0.3 of the Hydrator on Windows 10 and the Link Twitter Account button works as expected. What should happen when you click that button is your browser should open a window at Twitter and ask you to allow the Hydrator app to use your Twitter account in order to talk to the API. Can you tell me what your default web browser is? Are you able to click on links in other applications and have them open ok?

**Comment by edsu** [comment]
v0.0.4 of the Hydrator was just released which is now based on the most recent version of Electron. It's unlikely, but possible that the problem you are noticing will go away when using the new version. Could you give it a try and let us know?

**Comment by plumcola** [comment]
I have tried the v0.0.3 and v0.0.4 with opening Twitter on Chrome browser, and I failed. I closed the firewall. However, when I click the options in Help in Hydrator, it works successfully on opening relevant web pages on Chrome. Maybe I've set something wrong TAT

**Comment by kilitougo** [comment]
> I have tried the v0.0.3 and v0.0.4 with opening Twitter on Chrome browser, and I failed. I closed the firewall. However, when I click the options in Help in Hydrator, it works successfully on opening relevant web pages on Chrome. Maybe I've set something wrong TAT

same with you, are you using a VPN?

**Comment by edsu** [comment]
@plumcola thanks for testing v0.0.4 -- I'm sorry it didn't work. I made a small change to the way the Twitter URL is being opened. Can you try [v0.0.5](https://github.com/DocNow/hydrator/releases/tag/v0.0.5).

Also, do you have any security extensions installed in Chrome that might be preventing it from opening a Twitter URL?

I'm also curious if temporarily setting your default browser to Edge has any effect?

**Comment by edsu** [comment]
One other question for all of you who are having problems. Do you use a Twitter Desktop app that might be intercepting the open?

**Comment by ppival** [comment]
FWIW, I just ran v.0.05 on Win10 Education version 1909. Chrome is the default browser, with no extensions, and all worked as expected. Unlinked my account, connected to my work VPN and ran it all again and it still worked as expected. 

*seems* like Hydrator is ok, and it's a setting at the user end? Happy to try to test various configurations...

**Comment by edsu** [comment]
@ppival thank you for testing! that confirms my experience on a Win10 VM but it's really good to have another report of success.

**Comment by edsu** [comment]
@ppival thank you for testing! that confirms my experience on a Win10 VM but it's really good to have another report of success.

**Comment by edsu** [comment]
@ppival thank you for testing! that confirms my experience on a Win10 VM but it's really good to have another report of success.

**Comment by kilitougo** [comment]
Thanks for your efforts! However, after downloading the latest version, I still can not connect to my twitter account correctly. It asks me to input a pin, but no browser is opened. I can't input a pin.

**Comment by edsu** [comment]
@kilitougo Do you use antivirus software? What browser do you use, and do you have any security extensions installed in it?

**Comment by kilitougo** [comment]
I use windows defender, chrome of latest version and I open hydrator as administrator. Windows defender did warn me but I click run.

**Comment by edsu** [comment]
@kilitougo does temporarily disabling Windows Defender help at all? Also maybe there are some hints here? https://support.microsoft.com/en-us/help/4013218/windows-10-app-browser-control-in-windows-security

I'm sorry, but I am not a Windows administrator, and it is very difficult for me to help when I cannot replicate the same problem in my own Windows 10 environment. It is a longshot but maybe @kayiwa might have some other ideas?

**Comment by edsu** [comment]
I've just released [v0.0.8](https://github.com/DocNow/hydrator/releases/tag/v0.0.8) which should display the Twitter authorization URL you will need to point your browser at which should be handy when Hydrator is unable to open the browser itself.

@kilitougo @plumcola @jsutxhx would you be willing to give it a try and see if it helps?

https://github.com/DocNow/hydrator/releases/tag/v0.0.8

**Comment by 1eclipse** [comment]
hello, i do not know how to install and use hydrator. i have download hydrator from github. What should I do next? I'm confused. my machine is winOS. Can you give me some help? Thank you!!!

**Comment by edsu** [comment]
Please download a Windows installer from here:

https://github.com/DocNow/hydrator/releases/

Look for a release like:

* Hydrator-Setup-0.0.11.exe

Once you download and run that you should have a workable Hydrator on windows. I think many people were confused because they were attempting to build Hydrator from source which does not include keys. Instructions for adding your own keys have since been added to the README. I hope this helps. See #43 for more context.

**Comment by ELLEN15038979725** [comment]
Is this problem solved now? Has anyone successfully used it on win10? I installed several versions, but the button did not respond
