### ISSUE TITLE
Hydrator not reading tweets

### ISSUE THREAD

**Issue by abhincho** [DocNow/hydrator#30]
Hi
 I have installed hydrator on my windows system and have also linked my twitter account. But when I start hydrating no tweetIDs are read. 
![hydrator](https://user-images.githubusercontent.com/8470532/78708996-985f6080-7930-11ea-9472-c0abae02876c.JPG)
It was working before but my system got shutdown due to some power issues, and after I restating, now no tweetIDs are getting read.
Please help.

**Comment by edsu** [comment]
I wonder, has the tweet ids file moved? You might want to try adding it again?

**Comment by abhincho** [comment]
Thank you for your reply. I have added the file again and I also added a different file but in both cases the number of IDs read remains stuck at 0.

**Comment by edsu** [comment]
A few things to try:

- wait 30 minutes and start them again to see if you have been rate limited by Twitter
- relink your account to make sure your keys are working
- try with a smaller file of ids to make sure it isn't related to the size of those files you are working with

Generally speaking Hydrator isn't performing well with files that size until #15 is fixed. You may want to run a twarc hydrate process on a dedicated server instead.

**Comment by edsu** [comment]
Did you end up having any luck with any of the three approaches? I'd be happy to help with getting you set up with a long running twarc process if you are interested. I think it would probably take 4 days once it is set up correctly.

**Comment by abhincho** [comment]
It was a windows problem. I restarted the system and uninstalled hydrator. The I went to the C:\Users\user\AppData\Roaming  and deleted the hydrator folder.
Installed hydrator again and now it is running smoothly.

**Comment by edsu** [comment]
Oh good, I'm glad. I would like to know what got corrupted in the Hydrator, so if it happens again and you get any clues please reopen this ticket or add a new one.
