### ISSUE TITLE
How to Save Files

### ISSUE THREAD

**Issue by b-elsenheimer** [DocNow/hydrator#32]
Sorry in advance if this a basic question, but I am a textbook beginner when it comes to this sort of thing. I am able to read tweet IDs and hydrate them just fine. My confusion comes when I save the file of hydrated tweets. My goal is to open the hydrated tweets file in a Jupyter notebook (using python) and extract the tweet text to analyse it. What is the best way to save the hydrated tweets to be able to open them in this manner? This is for a school project, so any learning assistance would be appreciated.

**Comment by edsu** [comment]
@b-elsenheimer thanks for the question--I'm sure you're not alone. After the hydration has finished do you see a CSV button next to the dataset? If you click that it should convert the previously saved JSON data to a CSV file that you should be able to easily load in your Jupyter notebook with the csv module, or better yet, pandas.

Does that help at all?

**Comment by b-elsenheimer** [comment]
It should, my mistake was that I stopped the hydrating before it got through all the tweets (oops!). When I click that, it opens my file explorer (as it should, I'm assuming) so when I save it and name the file, should I include the '.csv' in the name or just type a name and it will automatically save as csv?

**Comment by edsu** [comment]
If you stop it hydrating before it's done I don't think you will see the CSV option. But yes, if you see the CSV option you should click it and see a prompt of where to save the CSV to. Definitely use the .csv extension, but be careful opening and saving it with Excel since it will likely corrupt the tweet id column.

**Comment by b-elsenheimer** [comment]
Got it, thank you for the quick responses!

**Comment by edsu** [comment]
Sure, thanks for asking the question here. Future confused users will appreciate it!
