### ISSUE TITLE
can't install using yarn

### ISSUE THREAD

**Issue by blas-ko** [DocNow/hydrator#33]
Hello, noob here. 

Tried to `git clone` and `yarn install` the source file but I get a `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'` error... 

I guess I should have docker or something similar run the app and then build the .yml somehow, but I'm a bit lost. 

What should I do? 

Thanks in advance!

**Comment by edsu** [comment]
Hi @blas-ko please download the installer for your [latest prebuilt release](https://github.com/DocNow/hydrator/releases) for your operating system unless you are wanting to help develop the Hydrator app.

**Comment by blas-ko** [comment]
Oh! I didn't notice the .deb file in the releases... how embarrassing, haha!

Many thanks for the quick response. 

Closing.

**Comment by edsu** [comment]
Let us know how it works. You are the first Linux install I've heard from!

**Comment by blas-ko** [comment]
Works like a charm 

![hydrator](https://user-images.githubusercontent.com/8909006/79771098-39351f00-8326-11ea-83a8-7624fe18edd8.png)

**Comment by edsu** [comment]
Yay!
