### ISSUE TITLE
Hydrator getting stuck on "add dataset" on Mac

### ISSUE THREAD

**Issue by sonoshah** [DocNow/hydrator#35]
I recently installed the latest release of hydrator and was able to open it up and link my twitter account, but when I try to add a dataset of tweets I get this error message. I might be missing something obvious here, but any help would be greatly appreciated!

<img width="711" alt="Screen Shot 2020-04-21 at 7 01 32 AM" src="https://user-images.githubusercontent.com/13369002/79875253-4261d280-839e-11ea-8bca-290800c19ce3.png">

**Comment by edsu** [comment]
Oh, just add the 'http://'  on the front!

**Comment by sonoshah** [comment]
HAH! @edsu, THANKS! I knew it must have been something obvious! Much appreciated!

**Comment by edsu** [comment]
Awesome! Please let us know how you fare with the Hydrator, either here in GitHub or in [Slack](https://bit.ly/docnow-slack).
