### ISSUE TITLE
Unexpected End of JSON input

### ISSUE THREAD

**Issue by mthomas30** [DocNow/hydrator#41]
I am getting this error upon trying to save as a CSV. It saves correctly as JSON and this only happens when I click the csv button. I've tried it on different sized data sets as well.
![error](https://user-images.githubusercontent.com/46981381/81967019-4fae5d80-95e8-11ea-886a-d4987b9451a5.png)

**Comment by mthomas30** [comment]
Uninstalled and restarted my computer and reinstalled and seems to be working now. Still not sure why this was but perhaps installed incorrectly.

**Comment by edsu** [comment]
I'm glad reinstalling worked. This appears to be similar to #39. @mthomas30 it if you have time it would be useful if you could add a comment there about what operating system you are running the hydrator on.
