### ISSUE TITLE
Report Twitter authorization errors.

### ISSUE THREAD

**Issue by ArthurBoschet** [DocNow/hydrator#43]
Hello, 

Thank you for sharing this app. However, I noticed that none of the buttons (datasets/ add/ settings and especially link twitter account) respond when being clicked. Is there anyway to fix this issue?

**Comment by edsu** [comment]
Yes, they only start to work after you've linked your twitter account. So it sounds like that isn't working for you?

**Comment by ArthurBoschet** [comment]
Yes, nothing happens when I click the Link Twitter Account button.

**Comment by edsu** [comment]
Ok, we've noticed this on Windows10 but not on OS X before. If you are able it would help us a great deal if you could open a terminal window, and run the Hydrator manually by typing this and enter:

    /Applications/Hydrator.app/Contents/MacOS/Hydrator

Then if you could reset your app and try to link again? Then look and see if there are any error messges in the terminal console that you could copy/paste here into this issue ticket? Thanks!

**Comment by edsu** [comment]
For more context this seems to be related to #38 and #27.

**Comment by ArthurBoschet** [comment]
After doing the above procedure this is the error message that is shown:

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
{
  statusCode: 401,
  data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
}

**Comment by edsu** [comment]
Thanks! If it's not too much trouble would it be possible to see a screenshot?

**Comment by ArthurBoschet** [comment]
![Screen Shot 2020-05-22 at 4 52 23 PM](https://user-images.githubusercontent.com/65563348/82680565-bc5ed300-9c4c-11ea-9d48-56ee0fa57012.png)

There is the screen shot of the command prompt

![Screen Shot 2020-05-22 at 4 54 50 PM](https://user-images.githubusercontent.com/65563348/82680737-fd56e780-9c4c-11ea-9f76-3ce6f7ce99cc.png)

And here is the app where nothing happens when I click the Link twitter Account and get this error

**Comment by edsu** [comment]
Perfect! Let me see if I can do a release that will display more information about what might be going on.

**Comment by ArthurBoschet** [comment]
Thank you!

**Comment by edsu** [comment]
Ok, I don't think this will fix your problem but it may provide some more details about what might be going wrong. Can you install [v0.0.10](https://github.com/DocNow/hydrator/releases/tag/v0.0.10) and run it manually again as you did before, and take a screenshot of the terminal window? Thank you!

https://github.com/DocNow/hydrator/releases/tag/v0.0.10

**Comment by ArthurBoschet** [comment]
![Screen Shot 2020-05-22 at 6 13 28 PM](https://user-images.githubusercontent.com/65563348/82687767-04cfbe00-9c58-11ea-9e2d-c91341ecd888.png)

the error message seems to change with: "error when getting Twitter auth url"

**Comment by edsu** [comment]
Interesting! That is an error message coming back from Twitter saying you aren't even allowed to have a URL to grant Hydrator permission to use your account.

Are you on a VPN by any chance? What ISP are you using?

**Comment by ArthurBoschet** [comment]
No I am not a VPN. The ISP I use is a French one called SFR.

**Comment by edsu** [comment]
I don't suppose you have a VPN that you could try from another network do you? As you can tell I'm grasping at straws as to why this would work for others but not you.

**Comment by ArthurBoschet** [comment]
Yeah thank you! I tried using a VPN to spoof my location to the US in case the cause of this problem was a difference in the legislation regarding access to data based on location. But that did not seem to solve the problem. I still got the exact same error message.

**Comment by edsu** [comment]
Wpw, ok. Just to make sure, could you reinstall and see if that helps?

**Comment by MaryamMoghadam** [comment]
Hey, I am in the US and tried to install the hydrator but I got the exact same errors as mentioned above. I followed the steps you mentioned but it didn't resolve my issue either. Were you able to solve this issue by any chance?

**Comment by edsu** [comment]
What platform are you on @MaryamMoghadam?

**Comment by MaryamMoghadam** [comment]
@edsu macOS Catalina Version 10.15.4

**Comment by edsu** [comment]
Weird. What ISP are you on? We havent been able to find a cause for why some people are experiencing this.

**Comment by MaryamMoghadam** [comment]
@edsu  It's XFINITY.

**Comment by MaryamMoghadam** [comment]
Yes I connected to two different Campus networks using VPN and ran hydrator manually but no luck.

**Comment by edsu** [comment]
Thanks for checking @MaryamMoghadam. Did you try the advice above to open a terminal window and see what the error message was?

...

If you are able, it would help us a great deal if you could open a terminal window, and run the Hydrator manually by typing this and enter:

/Applications/Hydrator.app/Contents/MacOS/Hydrator

Then if you could reset your app and try to link again? Then look and see if there are any error messages in the terminal console that you could copy/paste here into this issue ticket? Thanks!

**Comment by tencups** [comment]
I also receiving the same error.

**Comment by edsu** [comment]
@tencups what operating system are you using?

**Comment by tencups** [comment]
Windows 10, its actually working now i just installed then latest build
directly without cloning.

**Comment by edsu** [comment]
Ahah! Thank you, it never occurred to me that people would build themselves without getting developer keys. I think you have solved this! 

@MaryamMoghadam are you building from source too?

**Comment by SebasAas** [comment]
Hello! I have the same problem, when i click the "Link Twitter Account" button.

getting Twitter auth url
error when getting Twitter auth url
{
  statusCode: 401,
  data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
}

SO: I test it in 2 diferents PC both with Windows 10, and i have the same problem in both

**Comment by edsu** [comment]
Sorry to hear that @SebasAas. Did you build the app from source or use an installer?

**Comment by SebasAas** [comment]
Hello @edsu , from source, i clone the repo and install via command prompt.

**Comment by edsu** [comment]
@SebasAas Great! I apologize, our docs weren't really clear on what you need to do when building from source. I've just added a note to the [Develop](https://github.com/docnow/hydrator/#develop) README indicating that to build the Hydrator you need to go to register as a developer on Twitter, create an app, and put the app keys in a .env file in your project directory:

But, you should be able to download a prebuilt version from our releases page?

https://github.com/DocNow/hydrator/releases/tag/v0.0.11

The prebuilt version includes the Hydrator app's official keys for the Documenting the Now projec. So you are not required to register as a developer and create an app. We did have an issue with our v0.0.10 build process which didn't create a Windows installer, but that has now been resolved for v0.0.11.

Can you give v0.0.11 a try and let us know if it works for you?

**Comment by SebasAas** [comment]
@edsu Perfect, the prebuild version works for me, thanks a lot

**Comment by edsu** [comment]
Awesome, I'm so glad to finally close this issue! Thanks for verifying @SebasAas.

**Comment by ELLEN15038979725** [comment]
I downloaded this version --Hydrator-Setup-0.0.11.exe, but there was no response when I clicked the button，what should I do ?

**Comment by edsu** [comment]
What country do you live in? Are you able to use twitter.com normally?

**Comment by ELLEN15038979725** [comment]
China, and I can open twitter.com normally.

**Comment by edsu** [comment]
We have had other reports from people in China that the Hydrator fails to work. I thought Twitter was completely blocked in China?

**Comment by edsu** [comment]
@ELLEN15038979725 I'm assuming you use a proxy to connect to Twitter? What operating system are you using? Are you able to tell me if either HTTP_PROXY or HTTPS_PROXY are set in your system environment?

**Comment by ELLEN15038979725** [comment]
Yes, I can log in to Twitter with a proxy,and I use Windows 10.Both https_proxy and http_proxy are set in my system environment.

**Comment by edsu** [comment]
Ok, lets create a new issue for Hydrator to respect `https_proxy` and `http_proxy` when set in the environment. I actually did not know that was a common practice for clients to discover when a proxy was in use system wide.

**Comment by ELLEN15038979725** [comment]
I guess the reason may be the operating system. My friends can use Hydrator with macOS.I am also very curious about this issue, and I will continue to notice this question.Maybe I should try twarc.Anyway, thank you very much.

**Comment by edsu** [comment]
The operating system shouldn't matter too much. But the configuration of the operating system (vpn, proxy, etc) could make a significant difference!
