### ISSUE TITLE
Report JSON parsing errors.

### ISSUE THREAD

**Issue by cyborg-crypto** [DocNow/hydrator#44]
![Capture2](https://user-images.githubusercontent.com/55827453/82777066-9c0c5f80-9e6a-11ea-9e95-b9b31bf32f01.PNG)

**Comment by edsu** [comment]
Thanks for reporting this. It is more widespread than I thought! Could you look and see what the file size is on your .json file? I suspect it might be zero?

Also, this ticket is a duplicate of #42 so please follow that ticket for further information.

**Comment by cyborg-crypto** [comment]
Yeah sorry ed! as I didn't read the ticket #42. Yeah the size of the .json file is 0kb.
As you mentioned excel corrupts the twitter ids is there any other alternative way to get twitter ids from a relevant dataset and convert it into a text file?

**Comment by edsu** [comment]
How did you do it?
