### ISSUE TITLE
Nothing happens when I click the button "Link Twitter Account".

### ISSUE THREAD

**Issue by pamphilusTex** [DocNow/hydrator#49]
I installed the Hydrator on Windows (using Hydrator-Setup-0.0.12.exe). And then I clicked the button "Link Twitter Account" under settings, but there was no response. Is there anything else I need to do? 
I got some Twitter ids from the public data set. And I want to hydrate Twitter ID datasets. In addition, I applied for Twitter developer account but failed. So I only have a regular Twitter account and do not have a Twitter developer account. Can the Hydrator work without a Twitter developer account? Hope to get a reply soon, thank you!

**Comment by pamphilusTex** [comment]
I am using Windows 10 Pro and I tried to turn off the firewall and VPN. Moreover, I tried to install Hydrator-Setup-0.0.11.exe. And I ran the program from the command line. After I clicked the button "Link Twitter Account",  it showed:
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
getting Twitter auth url
error when getting Twitter auth url
Error: connect ETIMEDOUT 31.13.86.16:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '31.13.86.16',
  port: 443
}

**Comment by 1109LLL** [comment]
Exact same problem, can someone please help!

**Comment by edsu** [comment]
Are you able to view twitter.com in your browser?

**Comment by 1109LLL** [comment]
Hi thanks for replying! I am in China, and by using a VPN I can open twitter.com in the browser. However, I think the issue is the same as mentioned in the other issues thread: "Report network connection errors". The timeout error is probably due to the Great Firewall in China.
