### ISSUE TITLE
Authentication issue - TwitterPinAuth's requestAuthURL (through the "Link Twitter Account" button)

### ISSUE THREAD

**Issue by dem1995** [DocNow/hydrator#54]
I'm attempting to run the program through `yarn run develop`.

Hitting "Link Twitter Account" errors out in the requestAuthURL call (provided by `twitter-pin-auth`). For the specific output, I get
> getting Twitter auth url
> error when getting Twitter auth url
>{
>   statusCode: 401,
>   data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
>}

I receive this error on both Ubuntu 20.04.1 LTS and on Raspbian, both running on a 32-bit ARM Raspberry Pi B.

**Comment by edsu** [comment]
If you run it that way you will need to supply your own keys in the environment. See the note about keys [here](https://github.com/docnow/hydrator/#develop).
