### ISSUE TITLE
Feature Request: 32-bit ARM Debian/Ubuntu release

### ISSUE THREAD

**Issue by dem1995** [DocNow/hydrator#55]
Sorry if this isn't the right place for this, but I've spent most of the day today trying to get this running on a Raspberry Pi, and was hoping you might release a 32-bit ARM .deb release in the same manner as the others. I figure Raspberry Pis have to be a pretty popular IoT device for tasks like this, so I imagine it would be helpful to others too.

Regardless of whether you get around to it/ it's feasible, I'm grateful for this application- it's been incredibly helpful (the recovery feature is amazing! It really saved me when I lost power/internet, and when someone turned off the computer the process was running on). Thank you so much!

**Comment by chbdetta** [comment]
This app is built with the electron-builder, which supports building with armv7l arch. You just need to change how this app packs:
In `task/distribution.js` modify:

```
function packLinux() {
  return builder.build({
    targets: builder.Platform.LINUX.createTarget(null, builder.Arch.armv7l), // build for armv7l
  });
}
```

**Comment by dem1995** [comment]
Thank you! I will try this when I have some time.
