### ISSUE TITLE
Rate limit error message

### ISSUE THREAD

**Issue by georgetyler** [DocNow/hydrator#71]
Hello,

Thank you for developing this GUI -- it is proving very helpful. Apologies for the newbie question:

When the red 'Rate limited until ...' message surfaces, is there a way to discern whether that is because of A. hitting Twitter's rate limit (response 88) or B. the application successfully stopping just before the limit (so avoiding having Twitter serve you a limit response)?

**Comment by edsu** [comment]
Thanks! That message gets triggered when there are no more requests remaining according to the `x-rate-limit-remaining` HTTP Response Header that comes back with the API responses. You can see the logic [here](https://github.com/DocNow/hydrator/blob/master/app/utils/twitter.js#L114).  Does that help answer your question?

**Comment by georgetyler** [comment]
Sure -- I suppose my question is how to tell if the rate limit has occurred from [managing the `x-rate-limit-remaining` header](https://github.com/DocNow/hydrator/blob/64b3a24d33af4ce3e6d4536c25e3c91418a93734/app/utils/twitter.js#L114) or bumping into [`err.code ===88`](https://github.com/DocNow/hydrator/blob/64b3a24d33af4ce3e6d4536c25e3c91418a93734/app/utils/twitter.js#L132) a few lines down? 

(Apologies if I have misread the code and they are linked, or another misunderstanding -- I am assuming that these are distinct events)

**Comment by edsu** [comment]
You are right, they are indistinguishable from the user interface. Ordinarily unless there is a race going on between multiple hydration jobs, or your access keys are being used in another application, the 88 error case won't arise. But it's there just in case. You could run the app from the command line to see the log messages which do differ as you can probably see?

**Comment by georgetyler** [comment]
OK, that's reassuring -- I'm not confident enough with Electron to run it on the command line (unless there is a way to view the log in the UI console?), but it's good to know that the 88 error is rare when you're downloading one dataset at a time. Thanks for your help!

**Comment by edsu** [comment]
Sure thing! If you have ideas for how to better display to the user what is going on please feel free to reopen this.
