### ISSUE TITLE
Tweet id file error

### ISSUE THREAD

**Issue by YileAllenChen1** [DocNow/hydrator#72]
When I try to load my data it gives an error "invalid tweet id on line 1". I checked my csv file and its all tweet ids with nothing else.
Could you please help me?
![tweetidfileerror](https://user-images.githubusercontent.com/43359545/104795314-ca7cd900-5772-11eb-86d5-ffa70a9e4a63.jpg)

**Comment by edsu** [comment]
Hmm, can you share the file?

**Comment by YileAllenChen1** [comment]
Nvm, I noticed that excel was not displaying the ids correctly. I had to format the cells to text format and pasted the data again to display the correct ids, that solved the issue.

**Comment by edsu** [comment]
Beware, Excel will overflow the tweet ids, converting the last two digits to zeroes.
