### ISSUE TITLE
Stuck at Verifying 

### ISSUE THREAD

**Issue by Neptune-Wood** [DocNow/hydrator#76]
Hello, I added a dataset for hydration, then it starts to "verifying " the file and got stuck there. It has been verifying all night now, going nowhere.
The worst part is it kinda blocked the whole app, I cannot delete or pause this "verification", I tried exit and restart, tried to delete this file, the app takes no notice. When I restart it keeps "verifying". 
How can I fix this?

**Comment by edsu** [comment]
Eek, that's not good. Can you try the Reset button under Settings?

**Comment by Neptune-Wood** [comment]
ah nice, that does the trick, it is working now!
Don't know what blocked the hydrator last time, when I tried the same dataset again it verfied instantly and now it is hydrating

**Comment by edsu** [comment]
I'm glad that worked, and that it is working now. Thanks for reporting the issue so we know what is happening.
