### ISSUE TITLE
Hydrator stuck "verifying" file that no longer exists

### ISSUE THREAD

**Issue by kmlhpk** [DocNow/hydrator#92]
I've uninstalled and reinstalled Hydrator multiple times, long since deleted the file (small_data.txt) in question, and restarted my computer, but every time I open an instance of Hydrator it's still stuck on _"Verifying small_data.txt"_ with no option to stop it and select a different Tweet ID file.
![Screenshot_7](https://user-images.githubusercontent.com/44464908/118607472-89441680-b7b0-11eb-8695-a24379bfec89.jpg)

**Comment by kmlhpk** [comment]
Ah, resetting Twitter authentication in the Settings seems to have fixed it. Closing issue, hope this helps anyone in my position in the future.

**Comment by edsu** [comment]
Thanks for searching around and finding a fix for it. If you figure out a sequence of steps that causes it to reoccur please let us know!

**Comment by kmlhpk** [comment]
> 
> 
> Thanks for searching around and finding a fix for it. If you figure out a sequence of steps that causes it to reoccur please let us know!

I believe my issue occurred after the following:

1. Attempt to hydrate a large set of IDs, the first line of which was incorrectly formatted
2. Try again, with correct formatting, but Hydrator throws an error saying the ID was invalid
3. Pipe the first 10 IDs to a new file `small-data.txt` and delete the first ID
4. Try again, still no luck

I think that's more or less accurate - once my current ID list finished hydrating, I'll see if I can reproduce it and document my steps in more detail.
