### ISSUE TITLE
Invalid Tweet ID Error

### ISSUE THREAD

**Issue by rasaxton** [DocNow/hydrator#99]
I keep getting this error that I can't seem to clear. I followed the advice of Issue #72 but could not clear it still. Doesn't matter if I'm using .csv or .csv.gz. Any advice would be appreciated.
![image](https://user-images.githubusercontent.com/77939470/120897545-bee06080-c5f4-11eb-886c-d6ea92ba8998.png)

**Comment by edsu** [comment]
It won't read gz data. Can you screenshot the error you see when opening the. .csv?

**Comment by rasaxton** [comment]
> It won't read gz data. Can you screenshot the error you see when opening the. .csv?

Thanks! It's actually the same error message, whether i try a csv or gz

**Comment by edsu** [comment]
If you open your .csv file in your editor what is on the first line. If it's not a number you need to remove it and save it.

**Comment by edsu** [comment]
Unable to move forward with this without additional information. Please reopen if you can provide more feedback.
